<?php
/**
 * @file source_flyviews.install
 * Installation file for the FlyViews Source installation profile.
 */

/**
 * Implements hook_install().
 */
function source_flyviews_install() {
  theme_enable(array('seven'));
  // Set Seven as default theme.
  variable_set('theme_default', 'seven');
  // Set the site frontpage.
  variable_set('site_frontpage', 'drupalcons');

  // Do not show the author and date information for drupalcon nodes.
  variable_set('node_submitted_drupalcon', FALSE);
}

