<?php
/**
 * @file source_flyviews.install
 * Installation file for the FlyViews Source installation profile.
 */

/**
 * Implements hook_install().
 */
function source_flyviews_install() {
  // Use seven as our admin theme.
  theme_enable(array('seven'));
  $variables = array(
    'admin_theme' => 'seven',
    'node_admin_theme' => 1,
  );
  foreach ($variables as $key => $variable) {
    variable_set($key, $variable);
  }
}

